[package]
name = "sop"
version = "5.3.8"
edition = "2021"
description = "Rust bindings for Joltrin (formerly SOP)"
license = "MIT"
repository = "https://github.com/SharedCode/joltrin"

[dependencies]
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["serde", "v4"] }

[build-dependencies]
