basePath: /api/v1
info:
  contact: {}
paths:
  /storeitems/{key}:
    get:
      consumes:
      - application/json
      description: GetByKey responds with the details of the matching item as JSON.
      parameters:
      - description: Name of item to fetch
        in: path
        maxLength: 150
        minLength: 1
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: GetByKey returns an item from the store with a given key.
      tags:
      - StoreItems
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
