import re

with open("tools/httpserver/main.go", "r") as f:
    content = f.read()

new_block = """
// Filter out component stores generated by AI/Search engines (those containing slashes)
var visibleStores []sop.StoreInfo
for _, s := range stores {
gs.Contains(s.Name, "/") {
d(visibleStores, s)
.NewEncoder(w).Encode(visibleStores)
"""

content = content.replace("\tjson.NewEncoder(w).Encode(stores)\n", new_block)

with open("tools/httpserver/main.go", "w") as f:
    f.write(content)
