package memory

import (
	"context"
	"fmt"

	"testing"

	"github.com/sharedcode/sop"
	"github.com/sharedcode/sop/ai"
	"github.com/sharedcode/sop/inmemory"
)

type MockEmbedder struct{}

func (m *MockEmbedder) Name() string { return "MockEmbedder" }
func (m *MockEmbedder) Dim() int     { return 3 }
func (m *MockEmbedder) EmbedTexts(ctx context.Context, texts []string) ([][]float32, error) {
	if len(texts) == 0 {
		return nil, nil
	}
	vecs := make([][]float32, len(texts))
	for i, text := range texts {
		if text == "SubCat1" {
			vecs[i] = []float32{0.1, 0.2, 0.3} // Close to test vector
		} else {
			vecs[i] = []float32{0.5, 0.6, 0.7} // Default mismatch
		}
	}
	return vecs, nil
}

type MockLLM struct{}

func (m *MockLLM) Name() string                                 { return "MockLLM" }
func (m *MockLLM) EstimateCost(inTokens, outTokens int) float64 { return 0.0 }
func (m *MockLLM) Generate(ctx context.Context, prompt string, opts ai.GenOptions) (ai.GenOutput, error) {
	// Let's pretend it always categorizes into "MockCategory"
	return ai.GenOutput{Text: "MockCategory"}, nil
}

type FailingLLM struct{}

func (m *FailingLLM) Name() string                                 { return "FailingLLM" }
func (m *FailingLLM) EstimateCost(inTokens, outTokens int) float64 { return 0.0 }
func (m *FailingLLM) Generate(ctx context.Context, prompt string, opts ai.GenOptions) (ai.GenOutput, error) {
	return ai.GenOutput{}, fmt.Errorf("mock llm failure")
}

type FailingEmbedder struct{}

func (m *FailingEmbedder) Name() string { return "FailingEmbedder" }
func (m *FailingEmbedder) Dim() int     { return 3 }
func (m *FailingEmbedder) EmbedTexts(ctx context.Context, texts []string) ([][]float32, error) {
	return nil, fmt.Errorf("mock embedder failure")
}

func TestMemoryManager_IngestAndSleep(t *testing.T) {
	ctx := context.Background()

	catTree := inmemory.NewBtree[sop.UUID, *Category](true)
	vecTree := inmemory.NewBtree[VectorKey, Vector](true)
	itemTree := inmemory.NewBtree[sop.UUID, Item[string]](true)

	// Pull out the core Btree interface
	store := NewStore[string](catTree.Btree, vecTree.Btree, itemTree.Btree)
	mgr := NewMemoryManager[string](store, &MockLLM{}, &MockEmbedder{})

	// 1. Test IngestThought
	kbMgr := &KnowledgeBase[string]{Manager: mgr, Store: store}
	err := kbMgr.IngestThoughts(ctx, []Thought[string]{{Summaries: []string{"this is a brilliant thought about apples"}, Category: "", Data: "Apples are great"}}, "Nutritionist")
	if err != nil {
		t.Fatalf("IngestThought failed: %v", err)
	}

	cats, err := store.Categories(ctx)
	ok, err := cats.First(ctx)
	if !ok || err != nil {
		t.Fatalf("No categories were auto-generated by Ingest")
	}

	c, _ := cats.GetCurrentValue(ctx)
	if c.Name != "MockCategory" {
		t.Errorf("Expected auto-generated category 'MockCategory', got '%s'", c.Name)
	}

	// 2. Test SleepCycle
	mgr.sleepThreshold = 0
	err = mgr.SleepCycle(ctx)
	if err != nil {
		t.Fatalf("SleepCycle failed: %v", err)
	}
}

// Test edge cases to hit 100% coverage
