package memory

import (
	"context"
	"strings"
	"testing"

	"github.com/sharedcode/sop"
	"github.com/sharedcode/sop/inmemory"
)

// PlaybookRule dictates how the deterministic mock tools respond
type PlaybookRule struct {
	Keywords     []string
	CategoryName string
	Vector       []float32
}

// MockPlaybookEmbedder returns vectors mapped to specific keywords to guarantee deterministic geometries
type MockPlaybookEmbedder struct {
	Rules []PlaybookRule
}

func (e *MockPlaybookEmbedder) EmbedTexts(ctx context.Context, texts []string) ([][]float32, error) {
	var results [][]float32
	for _, text := range texts {
		matched := false
		for _, rule := range e.Rules {
			for _, kw := range rule.Keywords {
				if strings.Contains(text, kw) {
					results = append(results, rule.Vector)
					matched = true
					break // matched rule keyword
				}
			}
			if matched {
				break // outer loop
			}
		}
		if !matched {
			results = append(results, []float32{0.0, 0.0, 0.0})
		}
	}
	return results, nil
}

// MockPlaybookLLM dynamically creates new categories based on the text contents
type MockPlaybookLLM struct {
	Rules         []PlaybookRule
	GeneratedCats map[string]sop.UUID
	Embedder      *MockPlaybookEmbedder
}

func (m *MockPlaybookLLM) GenerateCategory(ctx context.Context, payload string) (*Category, error) {
	if m.GeneratedCats == nil {
		m.GeneratedCats = make(map[string]sop.UUID)
	}

	var catName string = "General (Generated)"

	for _, rule := range m.Rules {
		for _, kw := range rule.Keywords {
			if strings.Contains(payload, kw) {
				catName = rule.CategoryName
				break
			}
		}
	}

	id, exists := m.GeneratedCats[catName]
	if !exists {
		id = sop.NewUUID()
		m.GeneratedCats[catName] = id
	}

	// Use embedder to fetch center vector for the concept
	vecs, _ := m.Embedder.EmbedTexts(ctx, []string{catName})
	vector := vecs[0]

	return &Category{
		ID:           id,
		Name:         catName,
		Description:  "Generated by mock LLM",
		CenterVector: vector,
	}, nil
}

type CategorySeed struct {
	Name   string
	Vector []float32
}

type QueryExpect struct {
	Vector       []float32
	MatchPayload string
}

type PlaybookTestCase struct {
	Name           string
	Rules          []PlaybookRule
	SeedCategories []CategorySeed
	Payloads       []string
	ExpectedCats   []string
	Queries        []QueryExpect
}

func TestPlaybookSimulation_Harness(t *testing.T) {
	tests := []PlaybookTestCase{
		{
			Name: "Explicit Categories Security and Compliance Playbook",
			Rules: []PlaybookRule{
				{Keywords: []string{"System Playbook Root", "validate", "network", "System"}, CategoryName: "System Playbook Root (Generated)", Vector: []float32{0.5, 0.5, 0.5}},
				{Keywords: []string{"Security Requirements", "Security", "password", "JWT"}, CategoryName: "Security Requirements (Generated)", Vector: []float32{0.9, 0.1, 0.1}},
				{Keywords: []string{"Corporate Compliance", "Compliance", "Audit"}, CategoryName: "Corporate Compliance (Generated)", Vector: []float32{0.9, 0.9, 0.1}},
			},
			SeedCategories: []CategorySeed{
				{Name: "System Playbook Root", Vector: []float32{0.5, 0.5, 0.5}},
				{Name: "Security Requirements", Vector: []float32{0.9, 0.1, 0.1}},
				{Name: "Corporate Compliance", Vector: []float32{0.9, 0.9, 0.1}},
			},
			Payloads: []string{
				"Rule 1: Always validate user input before processing.",
				"Rule 2: Fallback to default configs when network fails.",
				"Security 1: Hash passwords using bcrypt before saving.",
				"Security 2: Validate JWT tokens on every authenticated API request.",
				"Audit logs must be preserved for Compliance.",
			},
			ExpectedCats: []string{
				"System Playbook Root",
				"Security Requirements",
				"Corporate Compliance",
			},
			Queries: []QueryExpect{}, // Tested earlier in logic, we can verify cats here
		},
		{
			Name: "Dynamic LLM Generated Cloud and DevSecOps Playbook",
			Rules: []PlaybookRule{
				{Keywords: []string{"validate", "network", "System"}, CategoryName: "System Playbook Root (Generated)", Vector: []float32{0.5, 0.5, 0.5}},
				{Keywords: []string{"Security", "password", "JWT"}, CategoryName: "Security Requirements (Generated)", Vector: []float32{0.9, 0.1, 0.1}},
				{Keywords: []string{"Compliance", "Audit"}, CategoryName: "Corporate Compliance (Generated)", Vector: []float32{0.9, 0.9, 0.1}},
			},
			SeedCategories: nil, // NONE - Must be dynamically generated
			Payloads: []string{
				"Always validate user input before processing. Network.",
				"Security 1: Hash passwords using bcrypt before saving. Verify JWT.",
				"Audit logs must be preserved for Compliance.",
			},
			ExpectedCats: []string{
				"System Playbook Root (Generated)",
				"Security Requirements (Generated)",
				"Corporate Compliance (Generated)",
			},
			Queries: []QueryExpect{
				{Vector: []float32{0.9, 0.1, 0.1}, MatchPayload: "Security 1:"},
				{Vector: []float32{0.5, 0.5, 0.5}, MatchPayload: "validate"},
				{Vector: []float32{0.9, 0.9, 0.1}, MatchPayload: "Audit"},
			},
		},
		{
			Name: "Dynamic LLM Generated Library Book Catalog",
			Rules: []PlaybookRule{
				{Keywords: []string{"AA-AF", "Alice", "Alchemist"}, CategoryName: "AA-AF", Vector: []float32{1.0, 0.0, 0.0}},
				{Keywords: []string{"AG-AL", "Animal", "Art"}, CategoryName: "AG-AL", Vector: []float32{0.0, 1.0, 0.0}},
				{Keywords: []string{"AM-AZ", "Avatar", "Awakening"}, CategoryName: "AM-AZ", Vector: []float32{0.0, 0.0, 1.0}},
				{Keywords: []string{"BA-BF", "Beowulf", "Beloved", "Brave"}, CategoryName: "BA-BF", Vector: []float32{-1.0, 0.0, 0.0}},
				{Keywords: []string{"BG-BL", "Bleak", "Blood"}, CategoryName: "BG-BL", Vector: []float32{0.0, -1.0, 0.0}},
				{Keywords: []string{"BM-BZ", "Brothers", "Book"}, CategoryName: "BM-BZ", Vector: []float32{0.0, 0.0, -1.0}},
			},
			SeedCategories: nil, // NONE - Must be dynamically generated
			Payloads: []string{
				"Alice's Adventures in Wonderland",
				"The Alchemist",
				"Animal Farm",
				"The Art of War",
				"Avatar: The Last Airbender",
				"The Awakening",
				"Beowulf",
				"Beloved",
				"Brave New World",
				"Bleak House",
				"Blood Meridian",
				"The Brothers Karamazov",
				"The Book Thief",
			},
			ExpectedCats: []string{
				"AA-AF",
				"AG-AL",
				"AM-AZ",
				"BA-BF",
				"BG-BL",
				"BM-BZ",
			},
			Queries: []QueryExpect{
				{Vector: []float32{0.0, 1.0, 0.0}, MatchPayload: "Animal Farm"},
				{Vector: []float32{0.0, -1.0, 0.0}, MatchPayload: "Bleak House"},
				{Vector: []float32{0.0, 0.0, 1.0}, MatchPayload: "Awakening"},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.Name, func(t *testing.T) {
			ctx := context.Background()

			cats := inmemory.NewBtree[sop.UUID, *Category](true)
			vecs := inmemory.NewBtree[VectorKey, Vector](true)
			items := inmemory.NewBtree[sop.UUID, Item[string]](true)

			s := NewStore[string](cats.Btree, vecs.Btree, items.Btree).(*store[string])
			s.SetTextIndex(&MockTextIndex{})

			embedder := &MockPlaybookEmbedder{Rules: tt.Rules}
			llm := &MockPlaybookLLM{Rules: tt.Rules, Embedder: embedder}
			s.SetLLM(llm)

			// 1. Seed explicit categories if applicable
			for _, seed := range tt.SeedCategories {
				cat := &Category{
					ID:           sop.NewUUID(),
					Name:         seed.Name,
					CenterVector: seed.Vector,
				}
				if _, err := s.AddCategory(ctx, cat); err != nil {
					t.Fatalf("Failed seeding category: %v", err)
				}
			}

			// 2. Insert Payloads
			for _, payload := range tt.Payloads {
				// Embed to trigger thresholds and knn logic
				eVecs, _ := embedder.EmbedTexts(ctx, []string{payload})
				item := Item[string]{
					ID:      sop.NewUUID().String(),
					Vector:  eVecs[0],
					Payload: payload,
				}
				if err := s.Upsert(ctx, item); err != nil {
					t.Fatalf("Failed to ingest playbook rule payload '%s': %v", payload, err)
				}
			}

			// 3. Validate Expected Categories Exist
			foundSystems := make(map[string]bool)
			ok, _ := s.categories.First(ctx)
			if ok {
				for {
					c, _ := s.categories.GetCurrentValue(ctx)
					foundSystems[c.Name] = true
					if ok, _ = s.categories.Next(ctx); !ok {
						break
					}
				}
			}

			for _, expectedCat := range tt.ExpectedCats {
				if !foundSystems[expectedCat] {
					t.Errorf("Missing expected playbook category: '%s'", expectedCat)
				}
			}

			// 4. Validate KNN Queries map correctly
			for _, q := range tt.Queries {
				hits, err := s.Query(ctx, q.Vector, &SearchOptions[string]{Limit: 3})
				if err != nil {
					t.Fatalf("KNN Query Failed: %v", err)
				}

				hasMatch := false
				t.Logf("hit length %d for vector %v", len(hits), q.Vector)
				for _, h := range hits {
					t.Logf("hit payload: %q", h.Payload)
				}
				for _, h := range hits {
					if strings.Contains(h.Payload, q.MatchPayload) {
						hasMatch = true
					}
				}
				if !hasMatch {
					t.Errorf("Vector %v query failed to map dynamically to payload '%s'", q.Vector, q.MatchPayload)
				}
			}
		})
	}
}
