#!/bin/bash
set -e

# Get the directory where the script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Change to the ai directory
cd "$SCRIPT_DIR"

echo "Building sop-etl..."
go build -o sop-etl ./cmd/sop-ai

echo "Building sop-ai..."
go build -o sop-ai ./cmd/agent

echo "---------------------------------------------------"
echo "1. Running ETL (Prepare)"
echo "---------------------------------------------------"
# This downloads the dataset and generates data/doctor_fallback.json
# The generated config will now include the nurse_local dependency.
./sop-etl prepare -url "https://raw.githubusercontent.com/itachi9604/healthcare-chatbot/master/Data/dataset.csv" -out "data/doctor_fallback.json"

echo ""
echo "---------------------------------------------------"
echo "2. Rebuilding Nurse Agent (Dependency)"
echo "---------------------------------------------------"
# The doctor agent depends on nurse_local for symptom translation.
./sop-etl ingest -config data/nurse_local.json -clean

echo ""
echo "---------------------------------------------------"
echo "3. Rebuilding Doctor Agent (Target)"
echo "---------------------------------------------------"
# We use the fallback config generated by the prepare step.
./sop-etl ingest -config data/doctor_fallback.json -clean

echo ""
echo "---------------------------------------------------"
echo "4. Sanity Test"
echo "---------------------------------------------------"
# We test with colloquial terms ("tummy hurt", "hot") to verify that 
# the nurse_local agent correctly translates them to medical terms 
# ("abdomen pain", "fever") before the doctor agent performs the lookup.
# Using the production config (doctor.json) and the agent binary.
echo "I have a tummy hurt and feel hot" | ./sop-ai -config data/doctor.json

echo ""
echo "---------------------------------------------------"
echo "5. Common Cold Test"
echo "---------------------------------------------------"
echo "I have a bad cough and a runny nose" | ./sop-ai -config data/doctor.json
